apiVersion: apps/v1
kind: Deployment
metadata:
  name: baremetal-operator
  namespace: capm3-system
spec:
  template:
    spec:
      containers:
      # Change the value of image field below to your controller image URL
      - image: quay.io/metal3-io/baremetal-operator:master
        name: baremetal-operator