apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capm3-system
resources:
- github.com/Nordix/baremetal-operator/deploy/operator/?ref=bmo-furkat
- github.com/Nordix/baremetal-operator/deploy/crds/?ref=bmo-furkat
- github.com/Nordix/baremetal-operator/deploy/rbac/?ref=bmo-furkat

configMapGenerator:
- behavior: merge
  literals:
  - DEPLOY_KERNEL_URL=${DEPLOY_KERNEL_URL}
  - DEPLOY_RAMDISK_URL=${DEPLOY_RAMDISK_URL}
  - IRONIC_ENDPOINT=${IRONIC_URL}
  - IRONIC_INSPECTOR_ENDPOINT=${IRONIC_INSPECTOR_URL}
  name: ironic-bmo-configmap

patchesStrategicMerge:
- bmo_image_patch.yaml