apiVersion: v1
data:
  tls.crt: ${IRONIC_CA_CERT_B64:-""}
kind: Secret
metadata:
  name: ironic-cacert
type: Opaque
---
apiVersion: v1
stringData:
  password: ${IRONIC_PASSWORD:-""}
  username: ${IRONIC_USERNAME:-""}
kind: Secret
metadata:
  name: ironic-credentials
type: Opaque
---
apiVersion: v1
stringData:
  password: ${IRONIC_INSPECTOR_PASSWORD:-""}
  username: ${IRONIC_INSPECTOR_USERNAME:-""}
kind: Secret
metadata:
  name: ironic-inspector-credentials
type: Opaque
