run:
  deadline: 5m
  skip-dirs:
    - mock*
  skip-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - errorlint
    - goconst
    - godot
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - whitespace
  # Run with --fast=false for more extensive checks
  fast: true
issues:
  exclude-rules:
    - path: api/v1alpha4/types\.go
      linters:
        - golint
    - path: test/e2e
      linters:
        - golint
    - path: _test\.go
      linters:
        - unused
    - linters:
        - staticcheck
      text: "SA1019:"
    # Dot imports for gomega or ginkgo are allowed
    # within test files.
    - path: _test\.go
      text: should not use dot imports
    - path: (test|e2e)/.*.go
      text: should not use dot imports
    - path: _test\.go
      text: cyclomatic complexity
    - path: baremetal/.*.go
      text: cyclomatic complexity
  include:
  - EXC0002 # include "missing comments" issues from golint
  max-issues-per-linter: 0
  max-same-issues: 0