language: go

services:
  - docker

env:
  global:
    - CONTAINER_RUNTIME=docker
  jobs:
    - TARGET=unit
    - TARGET=shellcheck
    - TARGET=markdownlint
    - TARGET=govet
    - TARGET=gofmt
    - TARGET=golint
    - TARGET=codegen

script:
- ./hack/${TARGET}.sh
