apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  creationTimestamp: null
  name: controlplane-0-config
  namespace: default
spec:
  clusterConfiguration:
    apiServer: {}
    certificatesDir: ""
    controlPlaneEndpoint: ""
    controllerManager: {}
    dns:
      type: ""
    etcd: {}
    imageRepository: ""
    kubernetesVersion: ""
    networking:
      dnsDomain: ""
      podSubnet: ""
      serviceSubnet: ""
    scheduler: {}
  initConfiguration:
    localAPIEndpoint:
      advertiseAddress: ""
      bindPort: 0
    nodeRegistration: {}
status: {}