on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - "v0.*.*"

name: Main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Generate release artifacts and notes
        run: |
          make release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/*
          body_path: releasenotes/releasenotes.md
